# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('upper_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lower_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lower_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('map_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date made')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mark_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('residents', models.IntegerField(default=-1)),
                ('mapid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Maps')),
            ],
        ),
    ]
